---

- name: Create custom scripts directory
  file:
    path: "{{ zabbix_agent__custom_scripts_directory|d('/opt/zabbix-agent-scripts') }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: ['docker-server', 'docker-server-monitoring']

- name: Install docker query cli file
  template:
    src: '{{ item }}.j2'
    dest: "{{ zabbix_agent__custom_scripts_directory|d('/opt/zabbix-agent-scripts') }}/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - docker_cli_containers.py
    - docker_cli_containers_stats.py
  tags: ['docker-server', 'docker-server-monitoring']

- name: Configure zabbix userparameters
  include_role:
    name: zabbix-agent
    tasks_from: types/user_parameter
  vars:
    zabbix_agent__userparameter:
      name: docker
      userparameters:
        - key: docker.containers.count
          command: "{{ zabbix_agent__custom_scripts_directory|d('/opt/zabbix-agent-scripts') }}/docker_cli_containers.py --count"
          sudo: true
          sudo_group: '{{ docker_server__socket_group }}'
          comment: get the current number of containers
        - key: docker.containers.discovery
          command: "{{ zabbix_agent__custom_scripts_directory|d('/opt/zabbix-agent-scripts') }}/docker_cli_containers.py --discovery --zabbix"
          sudo: true
          sudo_group: '{{ docker_server__socket_group }}'
          comment: get name of containers
        - key: docker.container[*]
          command: "{{ zabbix_agent__custom_scripts_directory|d('/opt/zabbix-agent-scripts') }}/docker_cli_containers.py '--container=$1' --zabbix"
          sudo: true
          sudo_group: '{{ docker_server__socket_group }}'
          comment: get information about a specific container
        - key: docker.container.name.stats[*]
          command: "{{ zabbix_agent__custom_scripts_directory|d('/opt/zabbix-agent-scripts') }}/docker_cli_containers_stats.py '--container-name=$1'"
          sudo: true
          sudo_group: '{{ docker_server__socket_group }}'
          comment: get stats about a specific container using docker api
        - key: docker.container.id.stats[*]
          command: "{{ zabbix_agent__custom_scripts_directory|d('/opt/zabbix-agent-scripts') }}/docker_cli_containers_stats.py '--container-id=$1'"
          sudo: true
          sudo_group: '{{ docker_server__socket_group }}'
          comment: get stats about a specific container using docker sys fs
      state: present
  tags: ['docker-server', 'docker-server-monitoring']
