---
- name: Install docker engine from web script
  shell: >
    curl -sSL "https://get.docker.com" | sh
  tags: ['docker']

- name: Create sysconfig/docker configuration
  become: yes
  template:
    src: docker.config.j2
    dest: /etc/default/docker
    owner: root
    group: root
    mode: 0640
  register: docker_config_result
  notify:
   - restart docker
  tags: ['docker']

- name: Create systemd configuration file
  become: yes
  copy:
    src: docker.service.debian
    dest: '/etc/systemd/system/docker.service'
  register: docker_init_result
  notify:
    - restart docker
  tags: ['docker']
