---
- name: Check if docker repository is installed
  register: docker_aptconf
  check_mode: no
  stat:
    path: /etc/apt/sources.list.d/docker.list
  tags: ['docker']

- name: Install docker engine from web script
  become: true
  shell: >
    curl -sSL "https://get.docker.com" | sh
  when: not docker_aptconf.stat.exists
  tags: ['docker']

- name: Install the latest version of docker engine
  become: yes
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ docker__packages_name }}'
  when: docker_aptconf.stat.exists
  tags: ['docker']

- name: Create sysconfig/docker configuration
  become: yes
  template:
    src: docker.config.j2
    dest: /etc/default/docker
    owner: root
    group: root
    mode: 0640
  register: docker_config_result
  notify:
   - restart docker
  tags: ['docker']

- name: Create systemd configuration file
  become: yes
  copy:
    src: docker.service.debian
    dest: '/etc/systemd/system/docker.service'
  register: docker_init_result
  notify:
    - restart docker
  tags: ['docker']
