---
- name: Add Docker repo for Yum based hosts
  become: yes
  copy:
    src: docker.repo
    dest: '/etc/yum.repos.d/docker.repo'
  tags: ['docker']

- name: Install the latest version of docker engine
  become: yes
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ docker__packages_name }}'
  tags: ['docker']
